### ISSUE TITLE
Basic Example TypeError

### ISSUE THREAD

**Issue by timpulver** [audiojs/audio#38]
When running the basic example I get a `TypeError`. 

Code:  
```
const Audio = require('audio')

Audio.load('./December.mp3').then(audio =>
  audio
    .trim()
    .normalize()
    .fade(.5)
    .fade(-.5)
    .save('sample-edited.wav')
).catch(err => { console.log(err); });
```

Output:  
```
this.buffer.each is not a function
    at Audio.trim (/Users/…/node_modules/audio/src/manipulations.js:282:15)
    at Audio.load.then.audio (/Users/…/index.js:23:6)
    at <anonymous>
``` 

I tried using the npm version as well as `npm i audiojs/audio`, with .wav and .mp3. Any ideas?

**Comment by dfcreative** [comment]
Please stay tuned, working hard on that.

**Comment by dy** [comment]
Ok it is fixed now
